#!/bin/bash
##################################################################
# Reverse Proxy for Minecraft server
#
# Copyright (c) 2023-2024 kokoroq. All rights reserved.
#
#
#                      Configure Tool
#
#
# PLEASE DO NOT EDIT
#
#                                               VERSION: 1.0
##################################################################

# Read QTY of server
cp server_list.txt server_list_edit.txt
sed -i '/^#/d' server_list_edit.txt
SERVER_QTY=`cat server_list_edit.txt | wc -l`

if [ $SERVER_QTY -eq 0 ]; then
    echo "No server information found"
    echo "Please fill in it on 'server_list.txt'"
    exit 1
fi

# Read server list

BACKUP_IFS=$IFS
IFS=$'\n'
i=0
touch ./.gen_port_list

while read LINE
do
    FORWARD_IPPORT=`echo $LINE | awk '{print $1}'`
    RS_PORT=`echo $LINE | awk '{print $2}'`
    echo "Generate server conf of $FORWARD_IPPORT to rp_minecraft.conf"

    # Generate rp_minecraft.conf
    echo "#################################" > ./docker/conf/rp_minecraft_$i.conf
    echo "#     Reverse Proxy setting" >> ./docker/conf/rp_minecraft_$i.conf
    echo "#" >> ./docker/conf/rp_minecraft_$i.conf
    echo "# DO NOT EDIT THIS FILE" >> ./docker/conf/rp_minecraft_$i.conf
    echo "#################################" >> ./docker/conf/rp_minecraft_$i.conf
    echo "error_log /var/log/nginx/rp_minecraft_$i.log info;" >> ./docker/conf/rp_minecraft_$i.conf
    echo "upstream mcinstance {" >> ./docker/conf/rp_minecraft_$i.conf
    echo "    server $FORWARD_IPPORT;" >> ./docker/conf/rp_minecraft_$i.conf
    echo "}" >> ./docker/conf/rp_minecraft_$i.conf
    echo "server {" >> ./docker/conf/rp_minecraft_$i.conf
    echo "    listen $RS_PORT;" >> ./docker/conf/rp_minecraft_$i.conf
    echo "    proxy_pass mcinstance;" >> ./docker/conf/rp_minecraft_$i.conf
    echo "    proxy_timeout 60s;" >> ./docker/conf/rp_minecraft_$i.conf
#    echo "    proxy_protocol on;" >> ./docker/conf/rp_minecraft_$i.conf
    echo "}" >> ./docker/conf/rp_minecraft_$i.conf

    # Save port number
    echo "$RS_PORT" >> ./.gen_port_list

    i=`expr $i + 1`
done < ./server_list_edit.txt

IFS=$BACKUP_IFS

rm -f ./server_list_edit.txt

echo "Generation complete!"
echo "Check ./docker/conf/rp_minecraft*.conf"